### ISSUE TITLE
Footer text not visible in dark mode

### ISSUE THREAD

**Issue by SundeepChand** [DSC-JSS-NOIDA/foss-events#172] opened 2021-03-18 07:20 UTC
**Describe the bug**
Footer text not visible in dark mode

**To Reproduce**
1. Select dark mode
2. Footer text is not visible

**Expected behavior**
The text on footer should have a lighter colour.

**Screenshots**
![cap](https://user-images.githubusercontent.com/34120932/111587283-fefb2880-87e7-11eb-9aa0-a9804b4a2b6d.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10 OS Version 2009 (Build 19042.867)
 - Browser Google Chrome
 - Version 89.0.4389.90 (Official Build) (64-bit)

I would like to work on this.

**Comment by PragatiVerma18** [comment] 2021-03-19 04:47
Hey @SundeepChand, thanks for bringing that to our notice. Please make the changes and drop a PR, assigning this issue to you.

**Comment by guptapranav4299** [comment] 2021-03-30 18:57
Hey @PragatiVerma18 I would like to work on this issue if it has not been resolved for a long time

**Comment by SundeepChand** [comment] 2021-03-31 05:43
Hi @guptapranav4299, feel free to work on this.
Sorry for the delay, I could not spare the time to work on this.

**Comment by rudrakshi99** [comment] 2021-03-31 08:47
> Hi @guptapranav4299, feel free to work on this.
> Sorry for the delay, I could not spare the time to work on this.

So, will I assign this issue to @guptapranav4299 ?

**Comment by SundeepChand** [comment] 2021-03-31 08:52
> So, will I assign this issue to @guptapranav4299 ?

Yes

**Comment by aditidewangan** [comment] 2021-04-15 15:12
I would like to work on this issue. I give it better color which is visible in dark mode. Please assign me because it seems that the issue is not resolved.

**Closed** 2021-04-21 17:15 UTC
Labels: GSSOC21, Level1
